"""Compare generated task quality against WebArena-style official tasks.

This module intentionally uses a deterministic rubric. It is not a learned
model; the goal is to make benchmark-readiness claims reproducible.
"""
from __future__ import annotations

from collections import Counter
from statistics import mean
from typing import Any
import re

from .quality import RAW_DSL_PATTERNS


def compare_task_sets(generated_tasks: list[dict], webarena_tasks: list[dict]) -> dict:
    generated = evaluate_generated_tasks(generated_tasks)
    webarena = evaluate_webarena_tasks(webarena_tasks)
    return {
        "rubric": {
            "instruction_quality": "Natural user-facing language, no raw DSL or character splitting.",
            "grounding": "Task binds to concrete sites/entities/inputs.",
            "verifiability": "Expected result can be checked deterministically.",
            "structure_complexity": "Evidence of multi-step, conditional, or constrained work.",
            "methodology_fit": "Alignment with this repo's intended structured workflow.",
        },
        "generated": generated,
        "webarena_official": webarena,
        "comparison": _comparison(generated, webarena),
        "recommendations": _recommendations(generated, webarena),
    }


def evaluate_generated_tasks(tasks: list[dict]) -> dict:
    scores = [_score_generated_task(t) for t in tasks]
    return _aggregate(tasks, scores, source="generated")


def evaluate_webarena_tasks(tasks: list[dict]) -> dict:
    scores = [_score_webarena_task(t) for t in tasks]
    return _aggregate(tasks, scores, source="webarena")


def _score_generated_task(task: dict) -> dict:
    description = task.get("task_description", "")
    actions = task.get("actions", [])
    gt_assertions = task.get("ground_truth", {}).get("assertions", [])
    verifier_checks = task.get("verifier", {}).get("checks", [])
    quality_passed = bool(task.get("quality_checks", {}).get("passed"))

    raw_dsl = _has_raw_dsl(description)
    char_split = _has_char_split(description)
    instruction_quality = 1.0
    if raw_dsl:
        instruction_quality -= 0.55
    if char_split:
        instruction_quality -= 0.35
    if len(description.split()) < 6:
        instruction_quality -= 0.10

    grounding = 1.0 if task.get("target_entity") else 0.0
    if not task.get("task_structure", {}).get("locator"):
        grounding -= 0.15

    verifiability = 1.0 if gt_assertions and verifier_checks else 0.0
    if len(gt_assertions) != len(verifier_checks):
        verifiability -= 0.35
    if not task.get("validation_status", {}).get("needs_backend_validation", True):
        verifiability -= 0.10

    structure_complexity = min(1.0, 0.25 + 0.18 * len(actions) + 0.12 * len(gt_assertions))
    if task.get("difficulty") in ("L4", "L5"):
        locator_count = len([
            k for k in task.get("task_structure", {}).get("locator", {})
            if not str(k).startswith("_")
        ])
        structure_complexity = min(1.0, structure_complexity + 0.08 * locator_count)

    methodology_fit = 1.0 if quality_passed else 0.35
    if raw_dsl or char_split:
        methodology_fit -= 0.30
    if not gt_assertions or not verifier_checks:
        methodology_fit -= 0.40

    return _bounded_scores({
        "instruction_quality": instruction_quality,
        "grounding": grounding,
        "verifiability": verifiability,
        "structure_complexity": structure_complexity,
        "methodology_fit": methodology_fit,
        "known_bug_free": 0.0 if raw_dsl or char_split else 1.0,
    })


def _score_webarena_task(task: dict) -> dict:
    intent = task.get("intent", "")
    eval_conf = task.get("eval", {})
    eval_types = eval_conf.get("eval_types", [])
    reference_answers = eval_conf.get("reference_answers", {})
    program_html = eval_conf.get("program_html", [])

    instruction_quality = 1.0
    if _has_raw_dsl(intent) or _has_char_split(intent):
        instruction_quality -= 0.50
    if len(intent.split()) < 4:
        instruction_quality -= 0.10

    grounding = 0.45
    if task.get("sites"):
        grounding += 0.20
    if task.get("start_url"):
        grounding += 0.15
    if task.get("instantiation_dict"):
        grounding += 0.20

    verifiability = 0.0
    if eval_types:
        verifiability += 0.45
    if reference_answers:
        verifiability += 0.25
    if program_html:
        verifiability += 0.25
    if eval_conf.get("reference_url"):
        verifiability += 0.15

    structure_complexity = _estimate_webarena_complexity(task)

    # Official WebArena tasks are not generated by this repo's blueprint
    # workflow, so methodology_fit here means benchmark-task completeness,
    # not conformance to our internal pipeline.
    methodology_fit = min(1.0, 0.35 + grounding * 0.30 + verifiability * 0.35)

    return _bounded_scores({
        "instruction_quality": instruction_quality,
        "grounding": grounding,
        "verifiability": verifiability,
        "structure_complexity": structure_complexity,
        "methodology_fit": methodology_fit,
        "known_bug_free": 0.0 if _has_raw_dsl(intent) or _has_char_split(intent) else 1.0,
    })


def _aggregate(tasks: list[dict], scores: list[dict], source: str) -> dict:
    if not tasks:
        return {"count": 0, "mean_scores": {}, "diagnostics": {}}

    score_keys = scores[0].keys()
    mean_scores = {k: round(mean(s[k] for s in scores), 3) for k in score_keys}
    overall = round(mean(mean_scores.values()), 3)

    descriptions = [
        t.get("task_description", t.get("intent", ""))
        for t in tasks
    ]
    diagnostics = {
        "raw_dsl_count": sum(_has_raw_dsl(d) for d in descriptions),
        "char_split_count": sum(_has_char_split(d) for d in descriptions),
        "mean_instruction_words": round(mean(len(d.split()) for d in descriptions), 2),
    }

    if source == "generated":
        diagnostics.update({
            "quality_failed_count": sum(not t.get("quality_checks", {}).get("passed") for t in tasks),
            "by_ability": dict(Counter(t.get("ability_dimension", "") for t in tasks)),
            "by_difficulty": dict(Counter(t.get("difficulty", "") for t in tasks)),
            "by_environment": dict(Counter(t.get("target_environment", "") for t in tasks)),
            "by_template": dict(Counter(t.get("task_structure", {}).get("task_template", "") for t in tasks)),
        })
    else:
        diagnostics.update({
            "by_site": dict(Counter(",".join(t.get("sites", [])) for t in tasks)),
            "by_eval_type": dict(Counter(e for t in tasks for e in t.get("eval", {}).get("eval_types", []))),
            "unique_intent_templates": len({t.get("intent_template_id") for t in tasks}),
        })

    return {
        "count": len(tasks),
        "overall_score": overall,
        "mean_scores": mean_scores,
        "diagnostics": diagnostics,
    }


def _comparison(generated: dict, webarena: dict) -> dict:
    gen_scores = generated.get("mean_scores", {})
    web_scores = webarena.get("mean_scores", {})
    keys = sorted(set(gen_scores) | set(web_scores))
    return {
        key: {
            "generated": gen_scores.get(key),
            "webarena_official": web_scores.get(key),
            "delta_generated_minus_webarena": (
                round(gen_scores[key] - web_scores[key], 3)
                if key in gen_scores and key in web_scores else None
            ),
        }
        for key in keys
    }


def _recommendations(generated: dict, webarena: dict) -> list[str]:
    recs = []
    gen_diag = generated.get("diagnostics", {})
    gen_scores = generated.get("mean_scores", {})
    web_scores = webarena.get("mean_scores", {})

    if gen_diag.get("quality_failed_count", 0):
        recs.append("Filter all quality-failed generated tasks before export.")
    if gen_diag.get("raw_dsl_count", 0) or gen_diag.get("char_split_count", 0):
        recs.append("Fix instruction rendering before comparing against official tasks.")
    if gen_scores.get("structure_complexity", 0) < web_scores.get("structure_complexity", 0):
        recs.append("Increase multi-step and condition-heavy generated tasks to approach official WebArena complexity.")
    if gen_scores.get("verifiability", 0) < web_scores.get("verifiability", 0):
        recs.append("Improve verifier coverage and backend-check templates.")
    if not recs:
        recs.append("Generated tasks pass the deterministic quality rubric; next add optional human/LLM review for semantic realism.")
    return recs


def _estimate_webarena_complexity(task: dict) -> float:
    intent = task.get("intent", "").lower()
    eval_types = task.get("eval", {}).get("eval_types", [])
    sites = task.get("sites", [])
    score = 0.25
    score += 0.10 * max(0, len(sites) - 1)
    score += 0.08 * len(eval_types)

    complex_markers = [
        "top-", "best-selling", "compare", "before", "after", "if ",
        "sort", "filter", "all ", "list", "change", "create", "delete",
        "update", "add", "remove", "find", "message", "review",
    ]
    score += 0.045 * sum(marker in intent for marker in complex_markers)
    score += min(0.20, len(intent.split()) / 100)
    return min(1.0, score)


def _has_raw_dsl(text: str) -> bool:
    return any(re.search(pattern, text) for pattern in RAW_DSL_PATTERNS)


def _has_char_split(text: str) -> bool:
    return bool(re.search(r"([A-Za-z],\s){3,}[A-Za-z]", text))


def _bounded_scores(scores: dict[str, float]) -> dict[str, float]:
    return {k: round(max(0.0, min(1.0, v)), 3) for k, v in scores.items()}
